import { Song } from "./interfaces/song";

export const SONGLIST: Song[] = [
  {
  track: 1,
  title: "Yesterday",
  composer: ["John Lennon", "Paul McCartney"],
  performer: ["The Beatles"],
  style: ["British Invasion", "Contemporary Pop/Rock", "Rock & Roll", "AM Pop", "Folk-Rock", "Psychedelic/Garage", "Soundtracks"],
  time: "02:05",
  year: "1965",
  thumbnails: "https://www.theaudiodb.com/images/media/artist/thumb/qpvwuv1347996168.jpg/preview",
},
  {
  track: 2,
  title: "Get Lucky",
  composer: ["Thomas Bangalter", "Guy-Manuel de Homem-Christo", "Nile Rodgers", "Pharrell Williams"],
  performer: ["Daft Punk"],
  style: ["Club/Dance"],
  time: "06:09",
  year: "2013",
  thumbnails: "https://www.theaudiodb.com/images/media/artist/thumb/yxvtsq1348517112.jpg/preview",
},
  {
  track: 3,
  title: "Blinding Lights",
  composer: ["Ahmad Balshe", "Oscar Holter", "Max Martin", "Jason Quenneville", "Abel Tesfaye"],
  performer: ["The Weeknd"],
  style: ["Alternative R&B", "Contemporary R&B", "Pop"],
  time: "03:24",
  year: "2020",
  thumbnails: "https://www.theaudiodb.com/images/media/artist/thumb/vtxqyp1495060298.jpg/preview",
},
  {
  track: 4,
  title: "You Only Live Twice - Main Title",
  composer: ["John Barry", "Leslie Bricusse"],
  performer: ["Nancy Sinatra"],
  style: ["Stage & Screen"],
  time: "02:45",
  year: "1967",
  thumbnails: "https://www.theaudiodb.com/images/media/artist/thumb/tswpxx1359208506.jpg/preview",
},
  {
  track: 5,
  title: "The Girl from Ipanema",
  composer: ["Norman Gimbel", "Antônio Carlos Jobim", "Vinícius de Moraes"],
  performer: ["Stan Getz", "João Gilberto feat: Antônio Carlos Jobim"],
  style: ["Bossa Nova", "Brazilian Traditions", "Brazilian Jazz", "Global Jazz", "Mainstream Jazz"],
  time: "05:17",
  year: "1964",
  thumbnails: "https://www.theaudiodb.com/images/media/artist/thumb/vpxxuy1403797507.jpg/preview",
},
  {
  track: 6,
  title: "Entre Dos Aguas",
  composer: ["Paco de Lucía", "José Torregrosa"],
  performer: ["Paco de Lucía"],
  style: ["Flamenco", "Western European Traditions", "Global Jazz", "Contemporary Flamenco", "Guitar Jazz", "Jazz Instrument"],
  time: "06:02",
  year: "1986",
  thumbnails: "https://www.theaudiodb.com/images/media/artist/thumb/luca-paco-de-5062a474ed9ca.jpg/preview",
},
  {
  track: 7,
  title: "Surf Rider",
  composer: ["Dick Dale"],
  performer: ["The Lively Ones"],
  style: ["", "Instrumental Rock", "Rock & Roll", "Surf"],
  time: "03:03",
  year: "1963",
  thumbnails: "https://www.theaudiodb.com/images/media/artist/thumb/lively-ones-the-515b4afb9a74f.jpg/preview",
},
  {
  track: 8,
  title: "Tamacun",
  composer: ["Tamacun"],
  performer: ["Rodrigo y Gabriela"],
  style: ["Alternative/Indie Rock"],
  time: "06:45",
  year: "2006",
  thumbnails: "https://www.theaudiodb.com/images/media/artist/thumb/rqvrvr1340524833.jpg/preview",
},
  {
  track: 9,
  title: "Sultans of Swing",
  composer: ["Mark Knopfler"],
  performer: ["Dire Straits"],
  style: ["Album Rock", "Contemporary Pop/Rock", "Rock & Roll"],
  time: "05:47",
  year: "1978",
  thumbnails: "https://www.theaudiodb.com/images/media/artist/thumb/qsrpru1479331864.jpg/preview",
},
  {
  track: 10,
  title: "Out Of Space",
  composer: ["Liam Howlett", "Kool Keith", "C. Miller", "M. Smith"],
  performer: ["The Prodigy"],
  style: ["Club/Dance", "Hardcore Techno", "Techno", "Rave"],
  time: "03:41",
  year: "1992",
  thumbnails: "https://www.theaudiodb.com/images/media/artist/thumb/qxvtxy1573380365.jpg/preview",
},

];
